### PR TITLE
Getting repository branches support

### PR DESCRIPTION
**Pull request by Filterer**
1) Expanded the GitDetails interface with two new methods that get the
branches of a repository or a specific branch based on the branch name.
Added the implementation of those methods to the GitApi class that
implements GitDetails.

2) To able to query for many branches, a class that can map the API
response for such a query to a list of branches with the result was
missing so the GitRefs class is added for that purpose. It has a list of
GitRef objects which is the existing class for a single branch.

3) Added two test methods in the GitApiTest for the new
functionality.

### CODE REVIEW

**Comment by shblue21** [comment]
Thanks for your contribution.

I think it's good to keep the repository owner's code formatting. (Difficult to check with diff)

**Comment by Filterer** [comment]
> Thanks for your contribution.
> 
> I think it's good to keep the repository owner's code formatting. (Difficult to check with diff)

I apologize for that, I have different formatting rules that are applied upon saving as autosave actions in my Eclipse. Since all the checks are passed I 'll wait till the pull request is merged.

**Comment by hkarthik7** [comment]
I appreciate that everyone use different IDEs, I will see if I can add an auto-code formatter before merging.

**Comment by Filterer** [comment]
Thanks for merging my pr.

**Pull request merged**
