### PR TITLE
Added uploadPackge method

### PR DESCRIPTION
**Pull request by shblue21**
# Azure DevOps java sdk pull request template guide

Thank you for your interest in contributing to this project.

## Description

I implemented the upload Package method of maven API.  
I changed getLocation to public for baseUrl combination  
(All apis start with /{org}/{project}/_apis but uploadPackages starts with /{org}/{project}/_packaging.)

## PR Checklist

- [x] Added help
- [x] Added unit test/s
- [x] Updated Change log

### CODE REVIEW

**Comment by hkarthik7** [comment]
Hey @shblue21 mate, thanks for raising the PR. I don't see any issue in making the `getLocationUrl()` method as `public`, but there is a reason for introducing **RestClientProvider** and **RestClient**. I kept in mind the **adapter** (RestClientProvider - adapter for RestClient and supplies what is required to send the request.) and **mediator** (RestClient - serves as mediator between base implementation and concrete classes that forms the Api. Also, provides the users an Api for calling any Azure DevOps REST Api.) patterns for these classes to separate the concerns. May be can we introduce a new method in **Instance** `enum` as `setSubdomain(String subdomainName)` and add that to `BaseInstance` to form the `BaseInstance` url as *https://subdomain.baseinstance* which will be *https://pkgs.dev.azure.com*. 

Then the request url can be formed accordingly in the method.
String baseInstance = Instance.BASEINSTANCE.setSubdomain("pkgs"); // This returns https://pkgs.dev.azure.com
StringBuilder requestUrl = new StringBuilder(baseInstance);
requestUrl.append({account})
requestUrl.append({org})
requestUrl.append("_packaging")
// Check for non-null and build your url.

Then you can send the request. This is just a suggestion and I'm open for modification if you feel that this isn't the right approach.

**Comment by shblue21** [comment]
@hkarthik7 Thanks for the feedback. I'll fix it as per your suggestion.

**Comment by shblue21** [comment]
Additionally, uploadPackage is not an officially guided API by Azure Devops.

**Comment by hkarthik7** [comment]
That is fine. LGTM, happy to merge. I think we need to tweak the tests.

**Comment by shblue21** [comment]
@hkarthik7 I will add logic to check if the package exists in the Maven, UPack test case, such as uploading or deleting artifacts.

**Comment by hkarthik7** [comment]
@shblue21, I agree, we can modify the tests to execute sequentially. I will give it a try 👍

**Pull request merged**
