### PR TITLE
Feature/upack

### PR DESCRIPTION
**Pull request by shblue21**
# Azure DevOps java sdk pull request template guide

Hello.

I have implemented a Universal Package API
and refactor maven API

Unviersal Package is an artifact that can be published/downloaded regardless of the language of the project.
https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/universal?view=azure-devops-rest-7.1

Regards,
## Description

Describe your PR in few words.

## PR Checklist

- [ ] Added help
- [x] Added unit test/s
- [ ] Updated Change log

### CODE REVIEW

**Comment by shblue21** [comment]
Could you please publish the Universal Package for testing? I will edit the test code.

**Comment by hkarthik7** [comment]
**@shblue21**, thanks for adding the UPack Api. I've published a packaged `universal-package` with version 1.0.0 and a package exists in recycle bin `universa-package` with version 1.0.0.

**Comment by shblue21** [comment]
@hkarthik7 Thanks for publishing for the test case.
I have a question because the test failed for an unknown reason.

Are Linux Test and Windows Test **running concurrently** in Azure pipeline?
The same test seems to succeed on Windows and fail on Linux.
So I guess the test is failing.

(e.g normal process : createProject(Linux) -> deleteatProject(Linux) 
createProject(Linux) ->createProject(Windows, Exception) -> deleteatProject(Linux) )

**Comment by hkarthik7** [comment]
@shblue21 that's right, tests for Windows and Linux runs parallel. I will update the tests so that it won't fail.

**Review by hkarthik7 — APPROVED** [review]
@shblue21, LGTM. Can also please add help contents?

**Comment by hkarthik7** [comment]
@shblue21 thanks for adding the help, appreciate it. Can you please resolve the conflicts for me to merge the changes?

**Comment by shblue21** [comment]
Sorry for the late reply. The commit 'Code reformat and clean up' of the main branch were reflected.

**Pull request merged**
