### PR TITLE
Added support for Git tag

### PR DESCRIPTION
**Pull request by shblue21**
#27 

# Azure DevOps java sdk pull request template guide

Thank you for your interest in contributing to this project.

## Description

- azure devops does not provide git api
- Implementation based on getRef and updateRef APIs

## PR Checklist

- [x] Added help
- [x] Added unit test/s
- [x] Updated Change log

### CODE REVIEW

**Comment by hkarthik7** [comment]
LGTM.

**Comment by shblue21** [comment]
@hkarthik7 , I'll try to resolve any conflicts regarding recent merges.

**Comment by hkarthik7** [comment]
@shblue21 Thanks mate.

**Comment by shblue21** [comment]
According to the Azure DevOps documentation, there are two ways to modify a GitRef.(Patch,Post)
1. Refs - Update Ref(Patch)
2. Refs - Update Refs(Post)

**Comment by hkarthik7** [comment]
@shblue21, I refactored the code and that introduced some breaking changes. Can you please review it and resolve the conflicts? I will merge the changes then.

**Comment by shblue21** [comment]
@hkarthik7 Of course. I will leave a comment again after work.

**Comment by shblue21** [comment]
@hkarthik7 I'm sorry for the late reply.
I modified GitTag method according to the Custom Header you added. 
Thank you

**Pull request merged**
