### PR TITLE
Added support for maven api

### PR DESCRIPTION
**Pull request by shblue21**
# Azure DevOps java sdk pull request template guide

Thank you for your interest in contributing to this project.

## Description

Hello. 

Implemented some API for artifact mvn type.
After the review, I will implement the remaining maven API and markdown
https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/maven?view=azure-devops-rest-7.1

Regards,

## PR Checklist

- [ ] Added help
- [x] Added unit test/s
- [ ] Updated Change log

### CODE REVIEW

**Review by hkarthik7 — CHANGES_REQUESTED** [review]
Please review the unit tests `shouldDeletePackageVersionFromRecycleBin` and `shouldDeletePackageVersion`

**Comment by hkarthik7** [comment]
Looks good to me.

**Comment by shblue21** [comment]
For actual testing, I need sample artifacts in Azure Artifact. 
Could you please upload a sample artifact? Or give me a PAT or add me to the project.

(https://dev.azure.com/harishkarthic/azure-devops-java-sdk)

**Comment by hkarthik7** [comment]
@shblue21 Thanks for the PR. I appreciate the time and effort that you've put in to update the SDK.

I have added few packages to the artifacts, modified and ran tests which looks good to me. Below are the package details, please feel free to add more tests. I've modified few bits in the **maven** package and pushed the code. We can wait until your next PR for Work items attachments and release the next version.

Feed Name: maven-feed
Package Details:

1. group id: org.HelloWorld; artifact id: HelloWorld; version: 1.0.1
2. group id: org.jack.click; artifact id: ClickJack; version: 1.5.0
3. group id: org.tester.maven; artifact id: MavenTester; version: 1.1.0

Package in recycle bin:

- group id: org.jack.click; artifact id: ClickJack; version: 2.5.0

**Comment by shblue21** [comment]
@hkarthik7 Thank you for your hard work. I will change the Test code with the artifacts you uploaded.

**Pull request merged**
